const PDFDocument = require('pdfkit');
const fs = require('fs');
const path = require('path');
const mongoose = require('mongoose');
const Report = require('../models/Report');
const User = require('../models/User');
const sendEmail = require('../utils/sendEmail');

// ─── Ensure reports directory exists ─────────────────────────────
const reportsDir = path.join(__dirname, '..', 'reports');
if (!fs.existsSync(reportsDir)) {
  fs.mkdirSync(reportsDir, { recursive: true });
}

// ─── Helper: Get document label ──────────────────────────────────
const getDocLabel = (type) => {
  const labels = {
    aadhaar: 'Aadhaar Card',
    pan: 'PAN Card',
    degree: 'Degree Certificate',
    employment: 'Employment Proof',
    address: 'Address Proof'
  };
  return labels[type] || type;
};

// ─── Helper: Get final decision ──────────────────────────────────
const getFinalDecision = (documents) => {
  const statuses = documents.map(d => d.status);
  if (statuses.some(s => s === 'rejected')) return 'Not Clear';
  if (statuses.every(s => s === 'verified')) return 'Clear';
  return 'Pending';
};

// ─── Generate PDF ─────────────────────────────────────────────────
const generatePDF = (reportData) => {
  return new Promise((resolve, reject) => {
    const doc = new PDFDocument({ margin: 50, size: 'A4' });
    const fileName = `BGV_Report_${reportData.candidateId}_${Date.now()}.pdf`;
    const filePath = path.join(reportsDir, fileName);
    const stream = fs.createWriteStream(filePath);

    doc.pipe(stream);

    // ── Header ──
    doc.rect(0, 0, doc.page.width, 80).fill('#667eea');
    doc.fillColor('white')
      .fontSize(22)
      .font('Helvetica-Bold')
      .text('VeriFlow BGV System', 50, 20);
    doc.fontSize(11)
      .font('Helvetica')
      .text('Background Verification Report', 50, 48);
    doc.text(`Generated: ${new Date().toLocaleDateString('en-IN', { day: '2-digit', month: 'long', year: 'numeric' })}`, 50, 62);

    doc.moveDown(3);

    // ── Candidate Info ──
    doc.fillColor('#1f2937')
      .fontSize(14)
      .font('Helvetica-Bold')
      .text('Candidate Information', 50, 100);

    doc.moveTo(50, 118).lineTo(545, 118).strokeColor('#e5e7eb').lineWidth(1).stroke();
    doc.moveDown(0.5);

    const infoY = 125;
    doc.fontSize(11).font('Helvetica-Bold').fillColor('#374151');

    const info = [
      { label: 'Full Name', value: reportData.candidateName },
      { label: 'Email Address', value: reportData.candidateEmail },
      { label: 'Position Applied', value: reportData.position },
      { label: 'Report Generated By', value: reportData.generatedByName || 'HR Manager' },
      { label: 'Report Date', value: new Date().toLocaleDateString('en-IN') }
    ];

    info.forEach((item, i) => {
      const y = infoY + (i * 22);
      doc.font('Helvetica-Bold').fillColor('#374151').fontSize(10).text(item.label + ':', 50, y);
      doc.font('Helvetica').fillColor('#6b7280').text(item.value, 200, y);
    });

    doc.moveDown(6);

    // ── Document Verification Status ──
    const tableY = infoY + (info.length * 22) + 20;

    doc.fillColor('#1f2937')
      .fontSize(14)
      .font('Helvetica-Bold')
      .text('Document Verification Status', 50, tableY);

    doc.moveTo(50, tableY + 18).lineTo(545, tableY + 18).strokeColor('#e5e7eb').lineWidth(1).stroke();

    // Table header
    const headerY = tableY + 25;
    doc.rect(50, headerY, 495, 22).fill('#f3f4f6');
    doc.fillColor('#374151').fontSize(10).font('Helvetica-Bold');
    doc.text('Document Type', 58, headerY + 6);
    doc.text('Status', 260, headerY + 6);
    doc.text('Upload Date', 360, headerY + 6);
    doc.text('Verified Date', 455, headerY + 6);

    // Table rows
    const docTypes = ['aadhaar', 'pan', 'degree', 'employment', 'address'];
    let rowY = headerY + 28;

    docTypes.forEach((type, i) => {
      const doc_data = reportData.documents.find(d => d.documentType === type);
      const status = doc_data?.status || 'not_uploaded';
      const uploadDate = doc_data?.uploadDate ? new Date(doc_data.uploadDate).toLocaleDateString('en-IN') : '—';
      const verifiedDate = doc_data?.verifiedAt ? new Date(doc_data.verifiedAt).toLocaleDateString('en-IN') : '—';

      // Row background
      if (i % 2 === 0) {
        doc.rect(50, rowY - 4, 495, 22).fill('#fafafa');
      }

      // Status color
      const statusColors = {
        verified: '#16a34a',
        rejected: '#dc2626',
        pending: '#d97706',
        not_uploaded: '#9ca3af'
      };

      const statusLabels = {
        verified: '✓ Verified',
        rejected: '✗ Rejected',
        pending: '⏳ Pending',
        not_uploaded: '— Not Uploaded'
      };

      doc.fillColor('#374151').fontSize(10).font('Helvetica');
      doc.text(getDocLabel(type), 58, rowY);
      doc.fillColor(statusColors[status] || '#9ca3af').font('Helvetica-Bold');
      doc.text(statusLabels[status] || status, 260, rowY);
      doc.fillColor('#6b7280').font('Helvetica');
      doc.text(uploadDate, 360, rowY);
      doc.text(verifiedDate, 455, rowY);

      rowY += 22;
    });

    // ── Final Decision ──
    const decisionY = rowY + 30;
    const decision = reportData.finalDecision;

    const decisionColors = {
      'Clear': { bg: '#f0fdf4', border: '#86efac', text: '#16a34a' },
      'Not Clear': { bg: '#fef2f2', border: '#fecaca', text: '#dc2626' },
      'Pending': { bg: '#fffbeb', border: '#fde68a', text: '#d97706' }
    };

    const colors = decisionColors[decision] || decisionColors['Pending'];

    doc.rect(50, decisionY, 495, 50).fill(colors.bg).stroke(colors.border);
    doc.fillColor('#374151').fontSize(12).font('Helvetica-Bold')
      .text('FINAL DECISION', 70, decisionY + 10);
    doc.fillColor(colors.text).fontSize(16).font('Helvetica-Bold')
      .text(decision.toUpperCase(), 70, decisionY + 26);

    // ── Footer ──
    const footerY = doc.page.height - 60;
    doc.moveTo(50, footerY).lineTo(545, footerY).strokeColor('#e5e7eb').lineWidth(1).stroke();
    doc.fillColor('#9ca3af').fontSize(9).font('Helvetica')
      .text('This report is generated by VeriFlow BGV System and is confidential.', 50, footerY + 10, { align: 'center' })
      .text('Aibi Tech © 2026', 50, footerY + 22, { align: 'center' });

    doc.end();

    stream.on('finish', () => resolve({ fileName, filePath }));
    stream.on('error', reject);
  });
};

// ─── Generate Report ──────────────────────────────────────────────
// @route   POST /api/reports/generate/:candidateId
// @access  HR only
exports.generateReport = async (req, res) => {
  try {
    const { candidateId } = req.params;

    // Validate candidateId
    if (!mongoose.Types.ObjectId.isValid(candidateId)) {
      return res.status(400).json({ success: false, message: 'Invalid candidate ID' });
    }

    // Get candidate from User model
    const candidate = await User.findById(candidateId);
    if (!candidate) {
      return res.status(404).json({ success: false, message: 'Candidate not found' });
    }

    if (candidate.role !== 'candidate') {
      return res.status(400).json({ success: false, message: 'User is not a candidate' });
    }

    // Get documents from Document model (Sachi's module)
    // Using dynamic model reference to avoid hard dependency
    let documents = [];
    try {
      const Document = mongoose.model('Document');
      documents = await Document.find({ candidateId }).sort({ uploadDate: 1 });
    } catch {
      // Document model not registered yet — use empty array
      documents = [];
    }

    // Map documents
    const docTypes = ['aadhaar', 'pan', 'degree', 'employment', 'address'];
    const mappedDocs = docTypes.map(type => {
      const doc = documents.find(d => d.documentType === type);
      return {
        documentType: type,
        status: doc?.status || 'not_uploaded',
        uploadDate: doc?.uploadDate || null,
        verifiedAt: doc?.verifiedAt || null
      };
    });

    // Calculate final decision
    const finalDecision = getFinalDecision(mappedDocs);

    // Generate PDF
    const reportData = {
      candidateId,
      candidateName: candidate.name,
      candidateEmail: candidate.email,
      position: candidate.position || 'Not specified',
      documents: mappedDocs,
      finalDecision,
      generatedByName: req.user.name
    };

    const { fileName, filePath } = await generatePDF(reportData);

    // Save report to DB
    const report = await Report.create({
      candidateId,
      candidateName: candidate.name,
      candidateEmail: candidate.email,
      position: candidate.position || 'Not specified',
      documents: mappedDocs,
      finalDecision,
      reportPath: fileName,
      generatedBy: req.user.id
    });

    // Send email to candidate
    try {
      await sendEmail({
        to: candidate.email,
        subject: 'VeriFlow BGV — Your Background Verification Report',
        html: `
          <div style="font-family: Inter, sans-serif; max-width: 480px; margin: 0 auto; padding: 32px;">
            <div style="background: linear-gradient(135deg, #667eea, #764ba2); padding: 24px; border-radius: 8px; text-align: center; margin-bottom: 24px;">
              <h1 style="color: white; margin: 0; font-size: 20px;">VeriFlow BGV System</h1>
            </div>
            <h2 style="color: #1f2937;">Your BGV Report is Ready</h2>
            <p style="color: #6b7280; margin: 16px 0;">
              Dear ${candidate.name},<br><br>
              Your Background Verification Report has been generated.
            </p>
            <div style="background: ${finalDecision === 'Clear' ? '#f0fdf4' : finalDecision === 'Not Clear' ? '#fef2f2' : '#fffbeb'}; border-radius: 8px; padding: 16px; margin: 16px 0; text-align: center;">
              <p style="font-size: 13px; color: #6b7280; margin: 0 0 4px;">Final Decision</p>
              <p style="font-size: 20px; font-weight: 700; color: ${finalDecision === 'Clear' ? '#16a34a' : finalDecision === 'Not Clear' ? '#dc2626' : '#d97706'}; margin: 0;">
                ${finalDecision.toUpperCase()}
              </p>
            </div>
            <p style="color: #6b7280; font-size: 13px;">
              Please login to your VeriFlow portal to download the full report.
            </p>
          </div>
        `
      });
    } catch (emailErr) {
      // Email failure should not block report generation
      console.log('Email sending failed:', emailErr.message);
    }

    res.status(201).json({
      success: true,
      message: 'BGV Report generated successfully',
      report: {
        id: report._id,
        candidateName: report.candidateName,
        finalDecision: report.finalDecision,
        generatedAt: report.generatedAt,
        downloadUrl: `/api/reports/download/${report._id}`
      }
    });

  } catch (err) {
    res.status(500).json({ success: false, message: err.message });
  }
};

// ─── Get Report by Candidate ──────────────────────────────────────
// @route   GET /api/reports/candidate/:candidateId
// @access  Protected (candidate sees own, hr sees all)
exports.getReportByCandidate = async (req, res) => {
  try {
    const { candidateId } = req.params;

    // Candidates can only see their own report
    if (req.user.role === 'candidate' && req.user.id !== candidateId) {
      return res.status(403).json({
        success: false,
        message: 'Access denied'
      });
    }

    const report = await Report.findOne({ candidateId })
      .sort({ generatedAt: -1 });

    if (!report) {
      return res.status(404).json({
        success: false,
        message: 'No report found for this candidate'
      });
    }

    res.status(200).json({
      success: true,
      report: {
        id: report._id,
        candidateName: report.candidateName,
        candidateEmail: report.candidateEmail,
        position: report.position,
        documents: report.documents,
        finalDecision: report.finalDecision,
        generatedAt: report.generatedAt,
        downloadUrl: `/api/reports/download/${report._id}`
      }
    });

  } catch (err) {
    res.status(500).json({ success: false, message: err.message });
  }
};

// ─── Get All Reports (HR view) ────────────────────────────────────
// @route   GET /api/reports
// @access  HR only
exports.getAllReports = async (req, res) => {
  try {
    const reports = await Report.find()
      .sort({ generatedAt: -1 })
      .populate('generatedBy', 'name email');

    res.status(200).json({
      success: true,
      count: reports.length,
      reports: reports.map(r => ({
        id: r._id,
        candidateName: r.candidateName,
        candidateEmail: r.candidateEmail,
        position: r.position,
        finalDecision: r.finalDecision,
        generatedAt: r.generatedAt,
        downloadUrl: `/api/reports/download/${r._id}`
      }))
    });

  } catch (err) {
    res.status(500).json({ success: false, message: err.message });
  }
};

// ─── Download Report PDF ──────────────────────────────────────────
// @route   GET /api/reports/download/:reportId
// @access  Protected
exports.downloadReport = async (req, res) => {
  try {
    const report = await Report.findById(req.params.reportId);

    if (!report) {
      return res.status(404).json({ success: false, message: 'Report not found' });
    }

    // Candidate can only download their own report
    if (req.user.role === 'candidate' &&
        report.candidateId.toString() !== req.user.id) {
      return res.status(403).json({ success: false, message: 'Access denied' });
    }

    const filePath = path.join(reportsDir, report.reportPath);

    if (!fs.existsSync(filePath)) {
      return res.status(404).json({ success: false, message: 'Report file not found' });
    }

    res.download(filePath, `BGV_Report_${report.candidateName.replace(/\s+/g, '_')}.pdf`);

  } catch (err) {
    res.status(500).json({ success: false, message: err.message });
  }
};
